<!DOCTYPE html><html lang="en" class="h-full"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sign in · FieldService CRM</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="h-full bg-slate-950"><main class="grid min-h-full lg:grid-cols-2">
<section class="relative hidden overflow-hidden bg-gradient-to-br from-blue-700 via-blue-900 to-slate-950 p-14 text-white lg:flex lg:flex-col lg:justify-between"><div class="absolute -right-32 -top-32 size-96 rounded-full bg-cyan-400/20 blur-3xl"></div><div class="relative flex items-center gap-3"><span class="grid size-12 place-items-center rounded-2xl bg-white/15 text-xl font-black ring-1 ring-white/20">FS</span><span class="text-xl font-bold">FieldService CRM</span></div><div class="relative max-w-xl"><p class="mb-5 text-sm font-semibold uppercase tracking-[.25em] text-cyan-300">One operational command center</p><h1 class="text-5xl font-bold leading-tight">Keep every technician, machine and service visit moving.</h1><p class="mt-6 text-lg leading-8 text-blue-100/80">Plan field work, track service quality and make faster decisions from a single professional workspace.</p></div><p class="relative text-sm text-blue-200/60">Technician & Field Service Management</p></section>
<section class="flex items-center justify-center bg-slate-50 p-6"><div class="w-full max-w-md"><div class="mb-8 lg:hidden"><span class="grid size-12 place-items-center rounded-2xl bg-blue-600 font-black text-white">FS</span></div><p class="text-sm font-semibold text-blue-600">WELCOME BACK</p><h2 class="mt-2 text-3xl font-bold text-slate-900">Sign in to your workspace</h2><p class="mt-2 text-slate-500">Enter your administrator credentials to continue.</p>
@if($errors->any())<div class="mt-6 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('login.store') }}" class="mt-8 space-y-5">@csrf
<div><label class="form-label">Email address</label><input class="form-input" type="email" name="email" value="{{ old('email') }}" required autofocus autocomplete="email" placeholder="admin@company.com"></div>
<div><label class="form-label">Password</label><input class="form-input" type="password" name="password" required autocomplete="current-password" placeholder="••••••••"></div>
<label class="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" name="remember" value="1" class="rounded border-slate-300 text-blue-600"> Keep me signed in</label>
<button class="btn-primary w-full justify-center py-3">Sign in securely</button></form>
<p class="mt-8 text-center text-xs text-slate-400">Protected by encrypted session authentication</p></div></section></main></body></html>
