<!DOCTYPE html><html lang="en" class="h-full"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sign in · FieldService CRM</title><script>document.documentElement.classList.toggle('dark',localStorage.getItem('theme')==='dark'||(!localStorage.getItem('theme')&&matchMedia('(prefers-color-scheme: dark)').matches));</script>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-full bg-slate-100 transition-colors dark:bg-slate-950"><main class="min-h-screen lg:grid lg:grid-cols-[1.08fr_.92fr] lg:gap-3 lg:p-3">
<section class="relative hidden min-h-[calc(100vh-1.5rem)] overflow-hidden rounded-[28px] bg-[#031532] text-white lg:block"><img src="{{ asset('images/login-technician-hero.png') }}" alt="Field technician using a tablet" class="absolute inset-0 size-full object-cover"><div class="absolute inset-0 bg-gradient-to-r from-[#031532] via-[#031532]/90 to-[#031532]/15"></div><div class="absolute inset-0 bg-gradient-to-t from-[#031532]/95 via-transparent to-[#031532]/20"></div>
<div class="relative z-10 flex min-h-[calc(100vh-1.5rem)] max-w-xl flex-col p-12 xl:p-16"><img src="{{ asset('images/fieldservice-logo.png') }}" alt="IHHH" class="h-20 w-56 rounded-2xl object-contain"><div class="mt-8"><h1 class="text-5xl font-bold leading-tight xl:text-6xl">Field Service<br><span class="bg-gradient-to-r from-blue-400 to-violet-400 bg-clip-text text-transparent">CRM</span></h1><div class="mt-5 h-1 w-16 rounded bg-violet-500"></div><p class="mt-5 text-lg leading-8 text-slate-200">Streamline operations. Empower your team.<br>Deliver exceptional service.</p></div>
<div class="mt-9 space-y-5">@foreach([['⚒','Manage Operations','Track jobs, assets and field activities in real-time.','bg-blue-600/30 text-blue-300'],['◇','Inventory Control','Manage parts, stock levels and inventory seamlessly.','bg-cyan-500/20 text-cyan-300'],['♧','Team Collaboration','Empower your team and improve communication.','bg-violet-500/25 text-violet-300'],['▥','Insights & Reports','Make data-driven decisions with powerful insights.','bg-amber-500/20 text-amber-300']] as [$icon,$heading,$copy,$tone])<div class="flex items-center gap-4"><span class="grid size-12 shrink-0 place-items-center rounded-full text-xl {{ $tone }}">{{ $icon }}</span><div><h3 class="font-bold">{{ $heading }}</h3><p class="mt-1 max-w-xs text-sm leading-6 text-slate-300">{{ $copy }}</p></div></div>@endforeach</div></div></section>
<section class="relative flex min-h-screen items-center justify-center bg-white p-6 transition-colors dark:bg-slate-950 lg:min-h-[calc(100vh-1.5rem)] lg:rounded-[28px]"><button type="button" onclick="toggleTheme()" class="absolute right-7 top-7 flex rounded-full border border-slate-200 bg-slate-50 p-1 shadow-sm dark:border-slate-700 dark:bg-slate-900" aria-label="Toggle light and dark mode"><span class="grid size-9 place-items-center rounded-full bg-white text-slate-500 shadow dark:bg-transparent dark:shadow-none">☀</span><span class="grid size-9 place-items-center rounded-full text-indigo-600 dark:bg-indigo-600 dark:text-white dark:shadow">☾</span></button>
<div class="w-full max-w-lg"><div class="text-center"><img src="{{ asset('images/fieldservice-logo.png') }}" alt="IHHH" class="mx-auto h-24 w-60 rounded-2xl object-contain"><p class="mt-3 text-xl font-semibold text-slate-900 dark:text-slate-100">Field Service CRM</p><h2 class="mt-8 text-4xl font-bold text-slate-950 dark:text-white">Welcome <span class="text-indigo-600">Back!</span></h2><p class="mt-3 text-lg text-slate-500 dark:text-slate-400">Sign in to continue to your account</p></div>
@if($errors->any())<div class="mt-6 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700 dark:border-rose-900 dark:bg-rose-950/40 dark:text-rose-300">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('login.store') }}" class="mt-8 space-y-5" x-data="{showPassword:false}">@csrf
<div class="relative"><span class="absolute left-4 top-1/2 -translate-y-1/2 text-xl text-slate-400">♙</span><input class="form-input py-4 pl-12 text-base" type="email" name="email" value="{{ old('email') }}" required autofocus autocomplete="email" placeholder="Email address"></div>
<div class="relative"><span class="absolute left-4 top-1/2 -translate-y-1/2 text-xl text-slate-400">♙</span><input class="form-input py-4 pl-12 pr-12 text-base" :type="showPassword?'text':'password'" name="password" required autocomplete="current-password" placeholder="Password"><button type="button" @click="showPassword=!showPassword" class="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400">◉</button></div>
<div class="flex items-center justify-between text-sm"><label class="flex items-center gap-2 text-slate-600 dark:text-slate-300"><input type="checkbox" name="remember" value="1" class="size-4 rounded border-slate-300 text-indigo-600"> Remember me</label><span class="text-indigo-600">Forgot Password?</span></div><button class="flex w-full items-center justify-center gap-4 rounded-xl bg-gradient-to-r from-blue-600 to-violet-600 px-5 py-4 text-base font-bold text-white shadow-lg shadow-indigo-500/20 transition hover:brightness-110">Sign In <span class="text-xl">→</span></button></form>
<div class="mt-8 flex items-center gap-5 text-slate-400"><span class="h-px flex-1 bg-slate-200 dark:bg-slate-800"></span><span>or</span><span class="h-px flex-1 bg-slate-200 dark:bg-slate-800"></span></div><p class="mt-7 text-center text-slate-500 dark:text-slate-400">Don't have an account? <span class="font-semibold text-indigo-600">Contact Administrator</span></p></div></section></main></body></html>
