@extends('layouts.app', ['title' => 'Dashboard'])
@section('content')
<div class="mb-7 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p class="text-2xl font-bold text-slate-900">Good {{ now()->hour < 12 ? 'morning' : (now()->hour < 17 ? 'afternoon' : 'evening') }}, {{ str(auth()->user()->name)->before(' ') }}</p><p class="mt-1 text-sm text-slate-500">Here is the latest view of your field operations.</p></div><div class="flex rounded-xl border border-slate-200 bg-white p-1 text-xs"><button class="rounded-lg bg-slate-900 px-3 py-2 font-medium text-white">Daily</button><button class="px-3 py-2">Weekly</button><button class="px-3 py-2">Monthly</button><button class="px-3 py-2">Yearly</button></div></div>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
@foreach($metrics as $metric)<article class="card group p-5"><div class="flex items-start justify-between"><div><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">{{ $metric['label'] }}</p><p class="mt-3 text-2xl font-bold text-slate-900">{{ ($metric['money'] ?? false) ? '₹'.number_format($metric['value'], 0) : number_format($metric['value']) }}</p></div><span class="grid size-9 place-items-center rounded-xl bg-{{ $metric['tone'] }}-50 text-{{ $metric['tone'] }}-600">↗</span></div><p class="mt-3 text-[11px] text-slate-400">Live operational total</p></article>@endforeach
</div>
<div class="mt-6 grid gap-6 xl:grid-cols-3"><section class="card p-6 xl:col-span-2"><div class="mb-5"><h3 class="font-bold text-slate-900">Work overview</h3><p class="text-xs text-slate-400">Completed and pending jobs over the last 7 days</p></div><div class="h-72"><canvas id="workChart"></canvas></div></section><section class="card p-6"><h3 class="font-bold text-slate-900">Job distribution</h3><p class="text-xs text-slate-400">Current workload by status</p><div class="mt-5 h-72"><canvas id="statusChart"></canvas></div></section></div>
<div class="mt-6 grid gap-6 xl:grid-cols-3"><section class="card p-6"><h3 class="font-bold text-slate-900">Today's attendance</h3><p class="text-xs text-slate-400">Technician availability</p><div class="mt-5 h-64"><canvas id="attendanceChart"></canvas></div></section><section class="card overflow-hidden xl:col-span-2"><div class="flex items-center justify-between border-b border-slate-100 p-6"><div><h3 class="font-bold text-slate-900">Recent users</h3><p class="text-xs text-slate-400">Latest team accounts</p></div>@can('viewAny', App\Models\User::class)<a href="{{ route('users.index') }}" class="text-sm font-semibold text-blue-600">View all →</a>@endcan</div><div class="divide-y divide-slate-100">@forelse($recentUsers as $user)<div class="flex items-center gap-3 px-6 py-4"><span class="grid size-9 place-items-center rounded-xl bg-slate-100 text-sm font-bold">{{ str($user->name)->substr(0,1) }}</span><div><p class="text-sm font-semibold text-slate-800">{{ $user->name }}</p><p class="text-xs text-slate-400">{{ $user->email }}</p></div><span class="ml-auto badge {{ $user->is_active ? 'badge-success' : 'badge-danger' }}">{{ $user->is_active ? 'Active' : 'Inactive' }}</span></div>@empty<div class="p-8 text-center text-sm text-slate-400">No users found.</div>@endforelse</div></section></div>
@endsection
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>window.renderDashboardCharts(@json($charts)))</script>@endpush
