@extends('layouts.app', ['title' => 'User Management'])
@section('content')
<div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 class="text-2xl font-bold text-slate-900">Users & access</h2><p class="text-sm text-slate-500">Manage CRM accounts, roles and account status.</p></div>@can('create', App\Models\User::class)<a href="{{ route('users.create') }}" class="btn-primary">+ Add user</a>@endcan</div>
<section class="card overflow-hidden"><form class="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row"><input name="search" value="{{ request('search') }}" class="form-input sm:max-w-sm" placeholder="Search name or email..."><select name="status" class="form-input sm:max-w-44"><option value="">All statuses</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option></select><button class="btn-secondary">Filter</button>@if(request()->hasAny(['search','status']))<a class="btn-secondary" href="{{ route('users.index') }}">Clear</a>@endif</form>
<div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-6 py-4">User</th><th class="px-6 py-4">Role</th><th class="px-6 py-4">Status</th><th class="px-6 py-4">Last login</th><th class="px-6 py-4 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100">
@forelse($users as $user)<tr class="hover:bg-slate-50/70"><td class="px-6 py-4"><div class="flex items-center gap-3"><span class="grid size-10 place-items-center rounded-xl bg-blue-50 font-bold text-blue-700">{{ str($user->name)->substr(0,1) }}</span><div><p class="font-semibold text-slate-800">{{ $user->name }}</p><p class="text-xs text-slate-400">{{ $user->email }}</p></div></div></td><td class="px-6 py-4">@foreach($user->roles as $role)<span class="badge badge-info">{{ $role->name }}</span>@endforeach</td><td class="px-6 py-4"><button data-toggle-user="{{ route('users.toggle',$user) }}" class="badge {{ $user->is_active ? 'badge-success' : 'badge-danger' }}">{{ $user->is_active ? 'Active' : 'Inactive' }}</button></td><td class="px-6 py-4 text-slate-500">{{ $user->last_login_at?->diffForHumans() ?? 'Never' }}</td><td class="px-6 py-4"><div class="flex justify-end gap-2"><a class="table-action" href="{{ route('users.show',$user) }}">View</a>@can('update',$user)<a class="table-action" href="{{ route('users.edit',$user) }}">Edit</a><a class="table-action" href="{{ route('users.permissions.edit',$user) }}">Permissions</a>@endcan @can('delete',$user)<form method="POST" action="{{ route('users.destroy',$user) }}" onsubmit="return confirm('Remove this user?')">@csrf @method('DELETE')<button class="table-action text-rose-600">Delete</button></form>@endcan</div></td></tr>
@empty<tr><td colspan="5" class="px-6 py-16 text-center"><p class="font-semibold text-slate-600">No users found</p><p class="mt-1 text-xs text-slate-400">Try changing your search or filters.</p></td></tr>@endforelse
</tbody></table></div><div class="border-t border-slate-100 p-4">{{ $users->links() }}</div></section>
@endsection
