<?php

use App\Http\Controllers\AmcPlanController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\JobCardController;
use App\Http\Controllers\MachineCategoryController;
use App\Http\Controllers\MachineController;
use App\Http\Controllers\MachineInventoryController;
use App\Http\Controllers\ModuleController;
use App\Http\Controllers\PartsInventoryController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ServiceReportController;
use App\Http\Controllers\ServiceRequestController;
use App\Http\Controllers\SkillController;
use App\Http\Controllers\TechnicianController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WorkAssignmentController;
use App\Http\Controllers\WorkforceController;
use App\Http\Controllers\WorkStatusController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/dashboard');
Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store'])->name('login.store');
});
Route::middleware(['auth', 'active'])->group(function () {
    Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::get('/modules/{module}', ModuleController::class)->name('modules.show');
    Route::get('/machine-documents/{document}', [MachineController::class, 'document'])->name('machine-documents.show');
    Route::delete('/machine-documents/{document}', [MachineController::class, 'destroyDocument'])->name('machine-documents.destroy');
    Route::get('/technicians/{technician}/photo', [TechnicianController::class, 'photo'])->name('technicians.photo');
    Route::get('/technicians/{technician}/id-card', [TechnicianController::class, 'idCard'])->name('technicians.id-card');
    Route::resources(['customers' => CustomerController::class, 'machines' => MachineController::class, 'technicians' => TechnicianController::class]);
    Route::get('/machine-inventory', [MachineInventoryController::class, 'index'])->name('machine-inventory.index');
    Route::get('/machine-inventory/create', [MachineInventoryController::class, 'create'])->name('machine-inventory.create');
    Route::post('/machine-inventory', [MachineInventoryController::class, 'transact'])->name('machine-inventory.store');
    Route::resource('skills', SkillController::class)->except('show');
    Route::resource('brands', BrandController::class)->except('show');
    Route::resource('departments', DepartmentController::class)->except('show');
    Route::resource('machine-categories', MachineCategoryController::class)->except('show');
    Route::resource('amc-plans', AmcPlanController::class)->except('show');
    Route::resource('service-requests', ServiceRequestController::class);
    Route::resource('assignments', WorkAssignmentController::class);
    Route::get('/job-cards', [JobCardController::class, 'index'])->name('job-cards.index');
    Route::get('/work-status', [WorkStatusController::class, 'index'])->name('work-status.index');
    Route::get('/work-status/{assignment}', [WorkStatusController::class, 'show'])->name('work-status.show');
    Route::patch('/work-status/{assignment}', [WorkStatusController::class, 'update'])->name('work-status.update');
    Route::get('/service-reports', [ServiceReportController::class, 'index'])->name('service-reports.index');
    Route::get('/service-reports/{serviceRequest}', [ServiceReportController::class, 'show'])->name('service-reports.show');
    Route::get('/parts', [PartsInventoryController::class, 'parts'])->name('parts.index');
    Route::get('/parts/create', [PartsInventoryController::class, 'createPart'])->name('parts.create');
    Route::post('/parts', [PartsInventoryController::class, 'savePart'])->name('parts.store');
    Route::delete('/parts/{part}', [PartsInventoryController::class, 'deletePart'])->name('parts.destroy');
    Route::get('/suppliers', [PartsInventoryController::class, 'suppliers'])->name('suppliers.index');
    Route::get('/suppliers/create', [PartsInventoryController::class, 'createSupplier'])->name('suppliers.create');
    Route::post('/suppliers', [PartsInventoryController::class, 'saveSupplier'])->name('suppliers.store');
    Route::delete('/suppliers/{supplier}', [PartsInventoryController::class, 'deleteSupplier'])->name('suppliers.destroy');
    Route::get('/inventory', [PartsInventoryController::class, 'inventory'])->name('inventory.index');
    Route::get('/inventory/create', [PartsInventoryController::class, 'createTransaction'])->name('inventory.create');
    Route::post('/inventory', [PartsInventoryController::class, 'transact'])->name('inventory.store');
    Route::get('/parts-issues', [PartsInventoryController::class, 'issues'])->name('parts-issues.index');
    Route::get('/parts-issues/create', [PartsInventoryController::class, 'createIssue'])->name('parts-issues.create');
    Route::post('/parts-issues', [PartsInventoryController::class, 'issue'])->name('parts-issues.store');
    Route::patch('/parts-issues/{partIssue}', [PartsInventoryController::class, 'updateIssue'])->name('parts-issues.update');
    Route::get('/job-parts', [PartsInventoryController::class, 'jobParts'])->name('job-parts.index');
    Route::get('/job-parts/create', [PartsInventoryController::class, 'createJobPart'])->name('job-parts.create');
    Route::post('/job-parts', [PartsInventoryController::class, 'usePart'])->name('job-parts.store');
    Route::get('/parts-requests', [PartsInventoryController::class, 'requests'])->name('parts-requests.index');
    Route::get('/parts-requests/create', [PartsInventoryController::class, 'createRequest'])->name('parts-requests.create');
    Route::post('/parts-requests', [PartsInventoryController::class, 'requestPart'])->name('parts-requests.store');
    Route::patch('/parts-requests/{partRequest}', [PartsInventoryController::class, 'actionRequest'])->name('parts-requests.update');
    Route::get('/attendance', [WorkforceController::class, 'attendance'])->name('attendance.index');
    Route::post('/attendance', [WorkforceController::class, 'saveAttendance'])->name('attendance.store');
    Route::get('/leave', [WorkforceController::class, 'leaves'])->name('leave.index');
    Route::post('/leave', [WorkforceController::class, 'storeLeave'])->name('leave.store');
    Route::patch('/leave/{leave}', [WorkforceController::class, 'updateLeave'])->name('leave.update');
    Route::get('/salary', [WorkforceController::class, 'salaries'])->name('salary.index');
    Route::post('/salary/generate', [WorkforceController::class, 'generateSalaries'])->name('salary.generate');
    Route::patch('/salary/{salary}/pay', [WorkforceController::class, 'paySalary'])->name('salary.pay');
    Route::get('/expenses', [WorkforceController::class, 'expenses'])->name('expenses.index');
    Route::post('/expenses', [WorkforceController::class, 'storeExpense'])->name('expenses.store');
    Route::patch('/expenses/{expense}', [WorkforceController::class, 'updateExpense'])->name('expenses.update');
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::put('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::put('/profile/password', [ProfileController::class, 'password'])->name('profile.password');
    Route::patch('/users/{user}/toggle', [UserController::class, 'toggle'])->name('users.toggle');
    Route::resource('users', UserController::class);
});
