@extends('layouts.app',['title'=>$machine->exists?'Edit Machine':'Add Machine']) @section('content')
<form method="POST" enctype="multipart/form-data" action="{{$machine->exists?route('machines.update',$machine):route('machines.store')}}" class="mx-auto max-w-6xl">@csrf @if($machine->exists)@method('PUT')@endif
<div class="mb-6 flex justify-between"><div><h2 class="text-2xl font-bold">{{$machine->exists?'Edit':'Add'}} Machine</h2><p class="text-sm text-slate-500">Asset identity, ownership, service cycle and documents.</p></div><button class="btn-primary">Save Machine</button></div><section class="card p-6"><div class="grid gap-5 md:grid-cols-2">
@include('master._field',['model'=>$machine,'name'=>'machine_code','label'=>'Machine Code','required'=>true]) @include('master._field',['model'=>$machine,'name'=>'machine_name','label'=>'Machine Name','required'=>true]) @include('master._field',['model'=>$machine,'name'=>'machine_type','label'=>'Machine Type','required'=>true]) @include('master._field',['model'=>$machine,'name'=>'brand','label'=>'Brand']) @include('master._field',['model'=>$machine,'name'=>'model','label'=>'Model']) @include('master._field',['model'=>$machine,'name'=>'serial_number','label'=>'Serial Number']) @include('master._field',['model'=>$machine,'name'=>'asset_number','label'=>'Asset Number'])
<div><label class="form-label">Customer *</label><select name="customer_id" class="form-input" required><option value="">Select customer</option>@foreach($customers as $c)<option value="{{$c->id}}" @selected(old('customer_id',$machine->customer_id)==$c->id)>{{$c->customer_code}} — {{$c->customer_name}}</option>@endforeach</select></div>
@foreach(['installation_date'=>'Installation Date','warranty_start'=>'Warranty Start','warranty_end'=>'Warranty End','amc_start'=>'AMC Start','amc_end'=>'AMC End'] as $n=>$l) @include('master._field',['model'=>$machine,'name'=>$n,'label'=>$l,'type'=>'date']) @endforeach
@include('master._field',['model'=>$machine,'name'=>'service_frequency','label'=>'Service Frequency (days)','type'=>'number']) @include('master._field',['model'=>$machine,'name'=>'status','label'=>'Status','type'=>'select','options'=>['active'=>'Active','inactive'=>'Inactive','under_maintenance'=>'Under Maintenance','decommissioned'=>'Decommissioned']]) @include('master._field',['model'=>$machine,'name'=>'site_name','label'=>'Site Name']) @include('master._field',['model'=>$machine,'name'=>'address','label'=>'Address','type'=>'textarea','wide'=>true]) @include('master._field',['model'=>$machine,'name'=>'city','label'=>'City']) @include('master._field',['model'=>$machine,'name'=>'state','label'=>'State']) @include('master._field',['model'=>$machine,'name'=>'pin_code','label'=>'PIN Code']) @include('master._field',['model'=>$machine,'name'=>'latitude','label'=>'Latitude','type'=>'number']) @include('master._field',['model'=>$machine,'name'=>'longitude','label'=>'Longitude','type'=>'number']) @include('master._field',['model'=>$machine,'name'=>'notes','label'=>'Notes','type'=>'textarea','wide'=>true])
<div><label class="form-label">Document Type</label><select class="form-input" name="document_type"><option value="photo">Machine Photo</option><option value="invoice">Invoice</option><option value="warranty">Warranty</option><option value="amc">AMC</option><option value="manual">Manual</option><option value="other">Other</option></select></div><div><label class="form-label">Documents</label><input class="form-input" type="file" name="documents[]" multiple></div>
</div></section><div class="mt-6 flex justify-end gap-3"><a href="{{route('machines.index')}}" class="btn-secondary">Cancel</a><button class="btn-primary">Save Machine</button></div></form>@endsection
