@extends('layouts.app',['title'=>'Job Cards Calendar'])
@section('content')
<div x-data="{open:false,day:'',jobs:[]}" class="relative"><div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 class="text-2xl font-bold">Job Cards Calendar</h2><p class="text-sm text-slate-500">Click any scheduled date to view its work list.</p></div><form><input type="month" name="month" value="{{ $month }}" class="form-input" onchange="this.form.submit()"></form></div>
<section class="card overflow-hidden"><div class="grid grid-cols-7 border-b bg-slate-50 text-center text-xs font-semibold uppercase text-slate-500 dark:bg-slate-800">@foreach(['Sun','Mon','Tue','Wed','Thu','Fri','Sat'] as $day)<div class="p-3">{{ $day }}</div>@endforeach</div><div class="grid grid-cols-7">
@for($blank=0;$blank<$start->dayOfWeek;$blank++)<div class="min-h-28 border-b border-r border-slate-100 bg-slate-50/50 dark:border-slate-800 dark:bg-slate-950/30"></div>@endfor
@for($day=1;$day<=$start->daysInMonth;$day++)@php $date=$start->copy()->day($day)->format('Y-m-d'); $jobs=$byDate->get($date,collect()); @endphp
<button type="button" @click="day=@js($start->copy()->day($day)->format('d M Y'));jobs=@js($jobs->values());open=true" class="min-h-28 border-b border-r border-slate-100 p-3 text-left transition hover:bg-blue-50 dark:border-slate-800 dark:hover:bg-slate-800"><span class="font-semibold">{{ $day }}</span>@if($jobs->isNotEmpty())<span class="mt-3 block rounded-lg bg-blue-600 px-2 py-1 text-xs font-semibold text-white">{{ $jobs->count() }} {{ Str::plural('work',$jobs->count()) }}</span><span class="mt-2 block truncate text-xs text-slate-500">{{ $jobs->first()->technician->name }}</span>@endif</button>
@endfor</div></section>
<div x-cloak x-show="open" class="fixed inset-0 z-[70] grid place-items-center bg-slate-950/60 p-4" @click.self="open=false"><div class="max-h-[80vh] w-full max-w-4xl overflow-y-auto rounded-2xl bg-white shadow-2xl dark:bg-slate-900"><div class="sticky top-0 flex items-center justify-between border-b bg-white p-5 dark:border-slate-700 dark:bg-slate-900"><div><h3 class="text-xl font-bold" x-text="day"></h3><p class="text-sm text-slate-500" x-text="`${jobs.length} scheduled works`"></p></div><button @click="open=false" class="text-2xl">×</button></div><div class="divide-y dark:divide-slate-800"><template x-for="job in jobs" :key="job.id"><div class="grid gap-3 p-5 hover:bg-slate-50 dark:hover:bg-slate-800 md:grid-cols-6"><a :href="`/assignments/${job.id}`"><span class="text-xs text-slate-400">Work ID</span><p class="font-semibold text-blue-600" x-text="job.assignment_code"></p></a><div><span class="text-xs text-slate-400">Customer</span><p x-text="job.service_request.customer.customer_name"></p></div><div><span class="text-xs text-slate-400">Technician</span><p x-text="job.technician.name"></p></div><div><span class="text-xs text-slate-400">Time</span><p x-text="`${job.start_time.slice(0,5)} – ${job.end_time.slice(0,5)}`"></p></div><div><span class="text-xs text-slate-400">Location / Status</span><p class="truncate" x-text="job.service_address"></p><span class="text-xs capitalize text-slate-400" x-text="job.status.replaceAll('_',' ')"></span></div><div class="flex flex-col justify-center gap-1.5"><span class="text-xs text-slate-400">Job Card</span><div class="flex gap-2"><a :href="`/assignments/${job.id}/job-card?view=1`" target="_blank" class="table-action">View</a><a :href="`/assignments/${job.id}/job-card`" class="table-action">Download</a></div></div></div></template></div></div></div></div>
@endsection
