@extends('layouts.app',['title'=>$customer->exists?'Edit Customer':'Add Customer']) @section('content')
<form method="POST" action="{{$customer->exists?route('customers.update',$customer):route('customers.store')}}" class="mx-auto max-w-6xl" x-data="{referType: '{{ old('refer_type',$customer->refer_type?:'self') }}'}">@csrf @if($customer->exists)@method('PUT')@endif
<div class="mb-6 flex items-end justify-between"><div><h2 class="text-2xl font-bold text-slate-900">{{$customer->exists?'Edit':'Add'}} Customer</h2><p class="text-sm text-slate-500">Complete customer identity, tax, contact and location information.</p></div><button class="btn-primary">Save Customer</button></div>
<section class="card p-6"><h3 class="mb-5 font-bold">Customer details</h3><div class="grid gap-5 md:grid-cols-2">
<div><label class="form-label">Customer ID</label><input class="form-input bg-slate-50" value="{{$customer->customer_code?:'Auto-generated after saving'}}" readonly><p class="mt-1 text-xs text-slate-400">First two letters of customer name + six random digits</p></div>
@include('master._field',['model'=>$customer,'name'=>'entry_type','label'=>'Entry Type','type'=>'select','required'=>true,'options'=>['crm'=>'CRM','leads'=>'Leads']])
@include('master._field',['model'=>$customer,'name'=>'customer_type','label'=>'Customer Type','type'=>'select','required'=>true,'options'=>['individual'=>'Individual','company'=>'Company','government'=>'Government']])
<div><label class="form-label">Refer Type *</label><select name="refer_type" class="form-input" x-model="referType" required><option value="self">Self</option><option value="staff">Staff</option></select></div>
<div x-show="referType==='staff'" x-cloak><label class="form-label">Staff Name *</label><select name="referred_by_technician_id" class="form-input" :required="referType==='staff'"><option value="">Select staff</option>@foreach($staff as $person)<option value="{{$person->id}}" @selected(old('referred_by_technician_id',$customer->referred_by_technician_id)==$person->id)>{{$person->employee_code}} — {{$person->name}}</option>@endforeach</select></div>
@include('master._field',['model'=>$customer,'name'=>'customer_name','label'=>'Customer Name','required'=>true]) @include('master._field',['model'=>$customer,'name'=>'company_name','label'=>'Company Name']) @include('master._field',['model'=>$customer,'name'=>'contact_person','label'=>'Contact Person']) @include('master._field',['model'=>$customer,'name'=>'date_of_birth','label'=>'Date of Birth','type'=>'date'])
@include('master._field',['model'=>$customer,'name'=>'mobile','label'=>'Mobile','required'=>true]) @include('master._field',['model'=>$customer,'name'=>'alternate_mobile','label'=>'Alternate Mobile']) @include('master._field',['model'=>$customer,'name'=>'email','label'=>'Email','type'=>'email']) @include('master._field',['model'=>$customer,'name'=>'whatsapp','label'=>'WhatsApp'])
@include('master._field',['model'=>$customer,'name'=>'gst_number','label'=>'GST Number']) @include('master._field',['model'=>$customer,'name'=>'pan_number','label'=>'PAN Number']) @include('master._field',['model'=>$customer,'name'=>'address','label'=>'Address','type'=>'textarea','wide'=>true,'required'=>true])
@include('master._field',['model'=>$customer,'name'=>'city','label'=>'City','required'=>true]) @include('master._field',['model'=>$customer,'name'=>'state','label'=>'State','required'=>true]) @include('master._field',['model'=>$customer,'name'=>'pin_code','label'=>'PIN Code','required'=>true])
<div class="md:col-span-2"><div class="mb-2 flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><label class="form-label">Customer Location</label><p class="text-xs text-slate-400">Search the address or click anywhere on the map to place the pin.</p></div><div class="flex gap-2"><button type="button" id="find-address" class="btn-secondary">Find Address</button><button type="button" id="current-location" class="btn-secondary">Use Current Location</button></div></div><input type="hidden" id="customer-latitude" name="latitude" value="{{old('latitude',$customer->latitude)}}"><input type="hidden" id="customer-longitude" name="longitude" value="{{old('longitude',$customer->longitude)}}"><div id="customer-map" class="h-96 w-full rounded-2xl border border-slate-200 bg-slate-100"><div class="grid h-full place-items-center p-6 text-center text-sm text-slate-500">Loading Google Map…</div></div><p id="map-coordinates" class="mt-2 text-xs text-slate-400"></p></div>
@include('master._field',['model'=>$customer,'name'=>'status','label'=>'Status','type'=>'select','options'=>['active'=>'Active','inactive'=>'Inactive']]) @include('master._field',['model'=>$customer,'name'=>'notes','label'=>'Notes','type'=>'textarea','wide'=>true])</div></section>
<section class="card mt-6 p-6" x-data="{contacts: {{Js::from(old('contacts',$customer->contacts->toArray()))}}}"><div class="mb-5 flex justify-between"><div><h3 class="font-bold">Additional contacts</h3><p class="text-xs text-slate-400">Add multiple people for this customer.</p></div><button type="button" class="btn-secondary" @click="contacts.push({name:'',designation:'',mobile:'',alternate_mobile:'',email:'',whatsapp:'',is_primary:false,notes:''})">+ Contact</button></div><template x-for="(contact,i) in contacts" :key="i"><div class="mb-3 grid gap-3 rounded-xl bg-slate-50 p-4 md:grid-cols-4"><input class="form-input" :name="`contacts[${i}][name]`" x-model="contact.name" placeholder="Name"><input class="form-input" :name="`contacts[${i}][designation]`" x-model="contact.designation" placeholder="Designation"><input class="form-input" :name="`contacts[${i}][mobile]`" x-model="contact.mobile" placeholder="Mobile"><input class="form-input" :name="`contacts[${i}][alternate_mobile]`" x-model="contact.alternate_mobile" placeholder="Alternate mobile"><input class="form-input" type="email" :name="`contacts[${i}][email]`" x-model="contact.email" placeholder="Email"><input class="form-input" :name="`contacts[${i}][whatsapp]`" x-model="contact.whatsapp" placeholder="WhatsApp"><input class="form-input" :name="`contacts[${i}][notes]`" x-model="contact.notes" placeholder="Notes"><div class="flex items-center justify-between"><label class="text-sm"><input type="checkbox" :name="`contacts[${i}][is_primary]`" value="1" x-model="contact.is_primary"> Primary</label><button type="button" class="text-sm text-rose-600" @click="contacts.splice(i,1)">Remove</button></div></div></template></section>
<div class="mt-6 flex justify-end gap-3"><a href="{{route('customers.index')}}" class="btn-secondary">Cancel</a><button class="btn-primary">Save Customer</button></div></form>@endsection
@push('scripts')
<script>
window.initCustomerMap = function () {
    const latInput = document.getElementById('customer-latitude');
    const lngInput = document.getElementById('customer-longitude');
    const coordinates = document.getElementById('map-coordinates');
    const existing = latInput.value && lngInput.value;
    const initial = existing ? {lat: Number(latInput.value), lng: Number(lngInput.value)} : {lat: 20.5937, lng: 78.9629};
    const map = new google.maps.Map(document.getElementById('customer-map'), {center: initial, zoom: existing ? 16 : 5, streetViewControl: false, mapTypeControl: true});
    const marker = new google.maps.Marker({position: initial, map, draggable: true, visible: Boolean(existing)});
    const geocoder = new google.maps.Geocoder();
    const setLocation = (position) => { const lat = Number(position.lat().toFixed(7)); const lng = Number(position.lng().toFixed(7)); latInput.value = lat; lngInput.value = lng; marker.setPosition({lat,lng}); marker.setVisible(true); map.panTo({lat,lng}); coordinates.textContent = `Selected location: ${lat}, ${lng}`; };
    map.addListener('click', event => setLocation(event.latLng));
    marker.addListener('dragend', event => setLocation(event.latLng));
    document.getElementById('find-address').addEventListener('click', () => { const parts = ['address','city','state','pin_code'].map(name => document.querySelector(`[name="${name}"]`)?.value).filter(Boolean); if (!parts.length) return alert('Enter the address first.'); geocoder.geocode({address: parts.join(', ')}, (results,status) => { if (status === 'OK' && results[0]) { setLocation(results[0].geometry.location); map.setZoom(17); } else alert('Google Maps could not find this address. Place the pin manually.'); }); });
    document.getElementById('current-location').addEventListener('click', () => { if (!navigator.geolocation) return alert('Location is not supported by this browser.'); navigator.geolocation.getCurrentPosition(position => { const point = new google.maps.LatLng(position.coords.latitude, position.coords.longitude); setLocation(point); map.setZoom(17); }, () => alert('Location permission was denied.')); });
    if (existing) coordinates.textContent = `Selected location: ${latInput.value}, ${lngInput.value}`;
};
</script>
@if(config('services.google_maps.key'))
<script async defer src="https://maps.googleapis.com/maps/api/js?key={{ urlencode(config('services.google_maps.key')) }}&callback=initCustomerMap"></script>
@else
<script>document.getElementById('customer-map').innerHTML='<div class="grid h-full place-items-center p-6 text-center text-sm text-amber-700">Google Maps API key is not configured. Add GOOGLE_MAPS_API_KEY to the server .env.</div>';</script>
@endif
@endpush
