@extends('layouts.app',['title'=>$customer->exists?'Edit Customer':'Add Customer']) @section('content')
<form method="POST" action="{{$customer->exists?route('customers.update',$customer):route('customers.store')}}" class="mx-auto max-w-6xl" x-data="{referType: '{{ old('refer_type',$customer->refer_type?:'self') }}'}">@csrf @if($customer->exists)@method('PUT')@endif
<div class="mb-6 flex items-end justify-between"><div><h2 class="text-2xl font-bold text-slate-900">{{$customer->exists?'Edit':'Add'}} Customer</h2><p class="text-sm text-slate-500">Complete customer identity, tax, contact and location information.</p></div><button class="btn-primary">Save Customer</button></div>
<section class="card p-6"><h3 class="mb-5 font-bold">Customer details</h3><div class="grid gap-5 md:grid-cols-2">
<div><label class="form-label">Customer ID</label><input class="form-input bg-slate-50" value="{{$customer->customer_code?:'Auto-generated after saving'}}" readonly><p class="mt-1 text-xs text-slate-400">First two letters of customer name + six random digits</p></div>
@include('master._field',['model'=>$customer,'name'=>'entry_type','label'=>'Entry Type','type'=>'select','required'=>true,'options'=>['crm'=>'CRM','leads'=>'Leads']])
@include('master._field',['model'=>$customer,'name'=>'customer_type','label'=>'Customer Type','type'=>'select','required'=>true,'options'=>['individual'=>'Individual','company'=>'Company','government'=>'Government']])
<div><label class="form-label">Refer Type *</label><select name="refer_type" class="form-input" x-model="referType" required><option value="self">Self</option><option value="staff">Staff</option></select></div>
<div x-show="referType==='staff'" x-cloak><label class="form-label">Staff Name *</label><select name="referred_by_technician_id" class="form-input" :required="referType==='staff'"><option value="">Select staff</option>@foreach($staff as $person)<option value="{{$person->id}}" @selected(old('referred_by_technician_id',$customer->referred_by_technician_id)==$person->id)>{{$person->employee_code}} — {{$person->name}}</option>@endforeach</select></div>
@include('master._field',['model'=>$customer,'name'=>'customer_name','label'=>'Customer Name','required'=>true]) @include('master._field',['model'=>$customer,'name'=>'company_name','label'=>'Company Name']) @include('master._field',['model'=>$customer,'name'=>'contact_person','label'=>'Contact Person'])
@include('master._field',['model'=>$customer,'name'=>'mobile','label'=>'Mobile','required'=>true]) @include('master._field',['model'=>$customer,'name'=>'alternate_mobile','label'=>'Alternate Mobile']) @include('master._field',['model'=>$customer,'name'=>'email','label'=>'Email','type'=>'email']) @include('master._field',['model'=>$customer,'name'=>'whatsapp','label'=>'WhatsApp'])
@include('master._field',['model'=>$customer,'name'=>'gst_number','label'=>'GST Number']) @include('master._field',['model'=>$customer,'name'=>'pan_number','label'=>'PAN Number']) @include('master._field',['model'=>$customer,'name'=>'address','label'=>'Address','type'=>'textarea','wide'=>true,'required'=>true])
@include('master._field',['model'=>$customer,'name'=>'city','label'=>'City','required'=>true]) @include('master._field',['model'=>$customer,'name'=>'state','label'=>'State','required'=>true]) @include('master._field',['model'=>$customer,'name'=>'pin_code','label'=>'PIN Code','required'=>true]) @include('master._field',['model'=>$customer,'name'=>'latitude','label'=>'Latitude','type'=>'number']) @include('master._field',['model'=>$customer,'name'=>'longitude','label'=>'Longitude','type'=>'number'])
@include('master._field',['model'=>$customer,'name'=>'status','label'=>'Status','type'=>'select','options'=>['active'=>'Active','inactive'=>'Inactive']]) @include('master._field',['model'=>$customer,'name'=>'notes','label'=>'Notes','type'=>'textarea','wide'=>true])</div></section>
<section class="card mt-6 p-6" x-data="{contacts: {{Js::from(old('contacts',$customer->contacts->toArray()))}}}"><div class="mb-5 flex justify-between"><div><h3 class="font-bold">Additional contacts</h3><p class="text-xs text-slate-400">Add multiple people for this customer.</p></div><button type="button" class="btn-secondary" @click="contacts.push({name:'',designation:'',mobile:'',alternate_mobile:'',email:'',whatsapp:'',is_primary:false,notes:''})">+ Contact</button></div><template x-for="(contact,i) in contacts" :key="i"><div class="mb-3 grid gap-3 rounded-xl bg-slate-50 p-4 md:grid-cols-4"><input class="form-input" :name="`contacts[${i}][name]`" x-model="contact.name" placeholder="Name"><input class="form-input" :name="`contacts[${i}][designation]`" x-model="contact.designation" placeholder="Designation"><input class="form-input" :name="`contacts[${i}][mobile]`" x-model="contact.mobile" placeholder="Mobile"><input class="form-input" :name="`contacts[${i}][alternate_mobile]`" x-model="contact.alternate_mobile" placeholder="Alternate mobile"><input class="form-input" type="email" :name="`contacts[${i}][email]`" x-model="contact.email" placeholder="Email"><input class="form-input" :name="`contacts[${i}][whatsapp]`" x-model="contact.whatsapp" placeholder="WhatsApp"><input class="form-input" :name="`contacts[${i}][notes]`" x-model="contact.notes" placeholder="Notes"><div class="flex items-center justify-between"><label class="text-sm"><input type="checkbox" :name="`contacts[${i}][is_primary]`" value="1" x-model="contact.is_primary"> Primary</label><button type="button" class="text-sm text-rose-600" @click="contacts.splice(i,1)">Remove</button></div></div></template></section>
<div class="mt-6 flex justify-end gap-3"><a href="{{route('customers.index')}}" class="btn-secondary">Cancel</a><button class="btn-primary">Save Customer</button></div></form>@endsection
